Fix --check-email parameter removing invalid email adresses
NetherlandsForensicInstitute/demeuk pull request #17
Opened 2021-12-22 16:21 UTC by rickvanderzwet

The testcase is written in an alternative format, which is more comprehensive in finding (and showing) any kind of difference in expected output.

2021-12-24 12:00 UTC, zyronix requested changes
Thank you for you contribution and thanks for fixing the failing e-mail detection!

I made some comments on the new way of testing that you have implemented. I like it, but would like you to make so small changes to it.

Also, once you have implemented those. Could you bump the version one minor release to 3.9.2?

2021-12-29 20:39 UTC, rickvanderzwet commented on bin/demeuk.py
> +EMAIL_REGEX = '.{1,64}@([a-zA-Z0-9_-]{1,63}\\.){1,3}[a-zA-Z]{2,24}'
Maximum currently known was 24. 6 looks as a sane default as well.

2021-12-29 20:43 UTC, rickvanderzwet commented on tests/test_app.py
> +        assert len(delta_lines) == 0
I will do some testing and make a seperate pull request for alternative testing method.

2022-01-07 10:03 UTC, zyronix approved these changes

2022-01-07 10:04 UTC, zyronix commented
Looks good, Only the entry:
`p@ssW0rd.me@Home` should still be kept in there. But because the code is already a major improvement I have merged it.

2022-01-07 10:04 UTC, merged